Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.disksize.size = '40GB'

#install vagrantPlugin: vagrant plugin install vagrant-disksize
#install vagrantplugin: vagrant plugin install vagrant-hostmanager
#install vagrantplugin: vagrant plugin install vagrant-vbguest

  config.vm.define "docker01" do |docker01|
   docker01.vm.box = "ubuntu/jammy64"
   docker01.vm.hostname = "docker01"
   docker01.vm.network "private_network", ip: "192.168.56.82"
   docker01.vm.network "public_network"
   docker01.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
     vb.cpus = 4
   end
      config.vm.provision "shell", path: "docker.sh"
#      config.vm.provision "shell", path: "K8s.sh"
#config.vm.provision "shell", inline: <<-SHELL
#!/bin/bash
   #SHELL
   end

  config.vm.define "docker02" do |docker02|
   docker02.vm.box = "ubuntu/focal64"
   docker02.vm.hostname = "docker02"
   docker02.vm.network "private_network", ip: "192.168.56.84"
   docker02.vm.network "public_network"
   docker02.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
     vb.cpus = 4
   end
   config.vm.provision "shell", path: "docker.sh"
   end
end
