name: Ay-micro

services:
  client:
    image: ayobamintl/client
    container_name: client
    ports:
      - "4200:4200"
    depends_on:
      - api
      - webapi
  api:
    restart: always
    image: ayobamintl/api
    container_name: api
    ports:
      - "5000:5000"
    depends_on:
      - nginx
      - emongo

  webapi:
    restart: always
    image: ayobamintl/webapi
    container_name: webapi
    ports:
      - "9000:9000"
    depends_on:
      - emartdb
  nginx:
    restart: always
    image: ayobamintl/nginx
    container_name: nginx
    ports:
      - "80:80"
  emongo:
    image: mongo:4
    container_name: emongo
    environment:
      - MONGO_INITDB_DATABASE=epoc
    ports:
      - "27017:27017"

  emartdb:
    image: mysql:8.0.33
    container_name: emartdb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=emartdbpass
      - MYSQL_DATABASE=books