---
- name: copy web configuration
  copy: 
    src: ~/static.conf
    dest: /etc/nginx/conf.d/

- name: copy web files
  ansible.builtin.copy: 
    src: /var/www/html/wordpress
    dest: /var/www/html/

- name: change file owner
  ansible.builtin.file:
    path: /var/www/html/wordpress/
    state: directory
    recurse: yes
    owner: nginx
    group: nginx
    mode: '0755'

