---
- name: deploy_artifact
  hosts: all
  become: yes
  tasks:
    - name: update webserver instances
      apt:
        name: "*"
        state: latest
        update_cache: yes
        cache_valid_time: 3600
# 2. Install essential packages
    - name: Install packages
      apt:
        name:
          - apache2
          - wget
          - unzip
        state: present
    
    - name: create workdir
      shell: mkdir /tmp/webfiles && cd /tmp/webfiles
    
    - name: download artifact
      shell: wget https://www.tooplate.com/zip-templates/2098_health.zip
    
    - name: unpack artifact
      shell: unzip 2098_health.zip > /dev/null
    
    - name: configure webserver
      shell: cp -r 2098_health/* /var/www/html/
    
    - name: restart service
      shell: systemctl restart apache2
    
    - name: clean-up
      shell: rm -rf /tmp/webfiles

   # - name: Set up UFW rules
    #  ufw:
     #   rule: allow
      #  port: "80"
       # proto: tcp
      #notify:
       # - enable ufw   