Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true


  config.vm.define "docker01" do |docker01|
   docker01.vm.box = "ubuntu/focal64"
   docker01.vm.hostname = "docker01"
   docker01.vm.network "private_network", ip: "192.168.56.82"
   docker01.vm.network "public_network"
   docker01.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
     vb.cpus = 4
   end
end
end
