Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true


  config.vm.define "docker01" do |docker01|
   docker01.vm.box = "ubuntu/focal64"
   docker01.vm.hostname = "docker01"
   docker01.vm.network "private_network", ip: "192.168.56.82"
   docker01.vm.network "public_network"
   docker01.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
     vb.cpus = 4
   end
config.vm.provision "shell", inline: <<-SHELL
#!/bin/bash
# Add Docker's official GPG key:
#sudo apt-get update
#sudo apt-get install ca-certificates curl -y
#sudo install -m 0755 -d /etc/apt/keyrings
#sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
#sudo chmod a+r /etc/apt/keyrings/docker.asc

# Add the repository to Apt sources:
#echo \
#  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
#  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
#  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
#sudo apt-get update

#sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
sudo apt-get update
#sudo apt-get install -y netcat git docker.io docker-compose python3 python3-pip
#sudo git clone -b development https://github.com/EyeSeeTea/d2-docker.git
#mkdir ~/app
#mv ~/d2-docker ~/app
#pip3 install ~/app/d2-docker
   SHELL
end
end
