Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.disksize.size = '40GB'

#install vagrantPlugin: vagrant plugin install vagrant-disksize
#install vagrantplugin: vagrant plugin install vagrant-hostmanager
#install vagrantplugin: vagrant plugin install vagrant-vbguest

  config.vm.define "web01" do |web01|
   web01.vm.box = "ubuntu/focal64"
   web01.vm.hostname = "web01"
   web01.vm.network "private_network", ip: "192.168.56.90"
   web01.vm.network "public_network", ip: "192.168.1.16"
   web01.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
     vb.cpus = 4
   end
  end

  config.vm.define "ansible" do |ansible|
   ansible.vm.box = "ubuntu/focal64"
   ansible.vm.hostname = "ansible"
   ansible.vm.network "private_network", ip: "192.168.56.91"
   ansible.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
     vb.cpus = 4
   end
  end
end
